version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-tools
    tty: true
    image: "<%= image %>"
    container_name: "<%= containerName %>"
    ports:
      - "8080:8080"
      - "2048:1024"
      - "2049:1025"
    volumes:
      - .:/swift-project <%if(images.length > 0){ %>
    links: <% images.forEach(image => { %>
      -  <%= image %> <%})} %>
    environment: <% envs.forEach(env => { for(key in env){ %>
      <%= key %>: <%= env[key] %><%}});%> <% images.forEach(image => {%>
  <%=image%>:
    image: <%=image%>
  <%});%>
